apiVersion: apps/v1
kind: Deployment
metadata:
  name: eric-website
  namespace: eric-website
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eric-website
    spec:
      containers:
      - image: ghcr.io/centerionware/cityparkliquors/website:afae8ae
        name: eric-website
        ports:
          - containerPort: 80
