version: '3'
services:
  nginx-site-1:
    image: nginx:custom
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./public:/usr/share/nginx/html
      - ./Store Pictures:/usr/share/nginx/html/Store Pictures/
    ports:
      - 8080:80
