name: Build and Publish Multi-Arch Docker Image

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push changes to another repo
      packages: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set short commit SHA as version
        id: version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-arch Docker image
        run: |
          IMAGE_TAG=ghcr.io/centerionware/cityparkliquors/website:${{ steps.version.outputs.VERSION }}-helm

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file other-repo/Dockerfile.helm \
            --push \
            --tag $IMAGE_TAG \
            ./

      - name: Update ArgoCD deployment manifest
        if: env.skip_build == 'false'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -euo pipefail

          REPO_URL="https://github.com/centerionware/cityparkliquors.git"
          BRANCH="argocd"
          FILE_PATH="cityparkliquors/website-nginx-deployment.yaml"
          IMAGE_PREFIX="ghcr.io/centerionware/cityparkliquors/website"
          SHORT_SHA="${{ steps.version.outputs.VERSION }}"
          FULL_SHA="${{ github.sha }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          NEW_TAG="${SHORT_SHA}-helm"

          git clone --single-branch --branch "$BRANCH" "$REPO_URL"
          cd deployment-repo

          sed -i "s|\(\s*- image: $IMAGE_PREFIX:\)[^[:space:]]*|\1$NEW_TAG|" "$FILE_PATH"
          echo "Updated image tag in $FILE_PATH:"
          cat "$FILE_PATH"

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          cat <<EOF > commit-message.txt
          Update image tag to $NEW_TAG

          Source Commit Metadata:
          - Author: $AUTHOR
          - SHA: $FULL_SHA
          - Commit: $COMMIT_URL

          Message:
          $COMMIT_MSG
          EOF

          git add "$FILE_PATH"
          git commit -F commit-message.txt
          git push origin "$BRANCH"

